#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L " _____  _____  _____  _____ ";
$L "|   __||     ||  |  ||  _  |";
$L "|__   ||  |  ||    -||   __|";
$L "|_____||_____||__|__||__|   ";
                                         
$L "Welcome to Android `getprop ro.build.version.release` / CyanogenMod-`getprop ro.cm.version`";
